on: [push]
  # schedule:
  #   - cron:  '* * * * 1'

jobs:
  check-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: webrtc-commit
        with:
          script: |
            const https = require('https');

            const commit = await new Promise(resolve => {
              https.get('https://chromiumdash.appspot.com/fetch_releases?channel=Stable&platform=Linux&num=1&offset=0', (resp) => {
                let data = '';

                resp.on('data', (chunk) => {
                  data += chunk;
                });

                resp.on('end', () => {
                  resolve(data);
                });

              })
            }).then(data => JSON.parse(data)[0]);
            return {
              version: commit.version,
              hash: commit.hashes.webrtc,
            };
          result-encoding: json
      
      - uses: action/github-script@v6
        id: version
        with: 
          script: |
            const version = process.env;
            console.dir(version);