on: [push]
  # schedule:
  #   - cron:  '* * * * 1'

jobs:
  check-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Parse current version
        run: |
          grep 'WEBRTC_SEMANTIC_VERSION' ./VERSION |
          cut -d'=' -f2 |
          {
            read version;
            echo "CURRENT_VERSION=${version}" >> $GITHUB_ENV;
          }

      - name: Get last stable version and hash
        uses: actions/github-script@v6
        id: webrtc-commit
        with:
          script: |
            const https = require('https');

            await new Promise(resolve => {
              https.get('https://chromiumdash.appspot.com/fetch_releases?channel=Stable&platform=Linux&num=1&offset=0', (resp) => {
                let data = '';

                resp.on('data', (chunk) => {
                  data += chunk;
                });

                resp.on('end', () => {
                  resolve(data);
                });

              })
            }).then(data => {
                const commit = JSON.parse(data)[0];
                core.exportVariable('LAST_VERSION', commit.version);
                core.exportVariable('WEBRTC_HASH', commit.hashes.webrtc);
              });

      - name: Check if the versions are different
        run: |
          if true
          then
            echo "The latest version ($CURRENT_VERSION) is already released!"
            exit 1
          fi
          echo "There is a new version!"
      
      # - uses: action/github-script@v6
      #   id: version
      #   with: 
      #     script: |
      #       const version = process.env;
      #       console.log(version);