on: [push]
  # schedule:
  #   - cron:  '* * * * 1'

jobs:
  check-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: webrtc-commit
        with:
          script: |
            const https = require('https');

            const commit = await new Promise((resolve) => {
              https.get('https://chromiumdash.appspot.com/fetch_releases?channel=Stable&platform=Linux&num=1&offset=0', (resp) => {
                let data = '';

                // A chunk of data has been received.
                resp.on('data', (chunk) => {
                  data += chunk;
                });

                // The whole response has been received. Print out the result.
                resp.on('end', () => {
                  console.log(JSON.parse(data));
                });

              })
            });
            // const commit = await fetch('https://chromiumdash.appspot.com/fetch_releases?channel=Stable&platform=Linux&num=1&offset=0').then(res => res.json()).then(data => data[0]);
            // const commit = await new Promise()
            // const result = {
            //   version: commit.version,
            //   hash: commit.hashes.webrtc,
            // };
            // return result;
          result-encoding: json
      
      # - uses: action/github-script@v6
      #   id: version
      #   with: 
      #     script: |
      #       const version = process.env;
      #       console.dir(version);