on: [push]
  # schedule:
  #   - cron:  '3 * * * *'

jobs:
  check-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "asd123axczasd123xczzcs" >> asd.dsa

      - name: Patch ./VERSION
        run: ./upgrade-ver.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          committer: GitHub <noreply@github.com>
          commit-message: Upgrade to  version
          branch: upgrade-to
          title: Upgrade to 
          body: Upgrade libwebrtc version to 
          labels: k::version
          draft: true
          delete-branch: true